site_name: Learning Odyssey
nav:
  - Home: index.md
  - Cloud:
      - Azure: azure/azure.md
      - AWS: aws/aws.md
      - GCP: gcp/gcp.md
  - Computer Science:
      - Software Architecture: computer_science/solid.md
  - Kubernetes:
      - Overview: kubernetes/overview.md
      - Cluster Setup: kubernetes/cluster_setup/cluster_setup.md
      - CKAD: kubernetes/ckad/ckad.md
      - CKA: kubernetes/cka/cka.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  pymdownx:
    superfences:
      copy_button: true

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences