site_name: Learning Odyssey
nav:
  - Home: index.md
  - Cloud:
      - Azure: azure/azure.md
      - AWS: aws/aws.md
      - GCP: gcp/gcp.md
  - Computer Science:
      - Software Architecture: computer_science/solid.md
  - Kubernetes:
      - Overview: kubernetes/kubernetes.md
      - Cluster Setup: kubernetes/cluster_setup/cluster_setup.md
      - CKAD: kubernetes/ckad/ckad.md
      - CKA: kubernetes/cka/cka.md
theme: readthedocs
